name = "back-end"
main = "src/index.js"
compatibility_date = "2024-05-01"

[vars]
# 카카오 로컬 API REST API 키를 설정하세요
# 카카오 개발자 콘솔(https://developers.kakao.com)에서 발급받을 수 있습니다
KAKAO_REST_API_KEY = "c5df0188ac6780e109cd2cba761bda15"

[ai]
binding = "AI"
